server.port=8080
logging.level.org.zalando.logbook.Logbook=TRACE
spring.main.banner-mode=OFF

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm
spring.datasource.username=ewm
spring.datasource.password=ewm
spring.datasource.driver-class-name=org.postgresql.Driver

stats.server.url=http://localhost:9090