DROP TABLE IF EXISTS comments;
CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT,
    text_on_moderation TEXT,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated TIMESTAMP WITHOUT TIME ZONE,
    event_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    status VARCHAR(30),
    moderator_id BIGINT,
    moderated TIMESTAMP WITHOUT TIME ZONE
);
