server.port=0
grpc.server.port=0
analyzer.kafka.bootstrap-servers=localhost:9092
analyzer.kafka.user-actions-topic=stats.user-actions.v1
analyzer.kafka.events-similarity-topic=stats.events-similarity.v1
analyzer.kafka.user-actions-group-id=ewm-analyzer-actions
analyzer.kafka.similarity-group-id=ewm-analyzer-similarity
analyzer.recommendations.neighbors=10
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6546/analyzer
spring.datasource.username=analyzer
spring.datasource.password=analyzer
management.endpoints.web.exposure.include=health,info
