server.port=0
logging.level.org.zalando.logbook.Logbook=TRACE
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/events
spring.datasource.username=events
spring.datasource.password=events
management.endpoints.web.exposure.include=health,info
grpc.client.collector.address=discovery:///collector
grpc.client.collector.enable-keep-alive=true
grpc.client.collector.keep-alive-without-calls=true
grpc.client.collector.negotiation-type=plaintext
grpc.client.analyzer.address=discovery:///analyzer
grpc.client.analyzer.enable-keep-alive=true
grpc.client.analyzer.keep-alive-without-calls=true
grpc.client.analyzer.negotiation-type=plaintext
