server.port=8080
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.routes[0].id=main-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://main-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/admin/**,/users/**,/events/**,/categories/**,/compilations/**
management.endpoints.web.exposure.include=health,info,gateway
