server.port=8080
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

spring.cloud.gateway.server.webflux.routes[0].id=comment-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://comment-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/admin/comments/**,/events/*/comments/**,/users/*/comments/**,/users/*/events/*/comments/**

spring.cloud.gateway.server.webflux.routes[1].id=request-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://request-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/*/requests/**

spring.cloud.gateway.server.webflux.routes[2].id=user-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/admin/users/**

spring.cloud.gateway.server.webflux.routes[3].id=event-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://event-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/admin/categories/**,/admin/compilations/**,/admin/events/**,/categories/**,/compilations/**,/events/**,/users/*/events/**

management.endpoints.web.exposure.include=health,info,gateway

spring.cloud.gateway.server.webflux.routes[4].id=stats-server
spring.cloud.gateway.server.webflux.routes[4].uri=lb://stats-server
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/hit,/stats,/stats/**
