server.port=0
logging.level.org.zalando.logbook.Logbook=TRACE
spring.main.banner-mode=OFF
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm
spring.datasource.username=ewm
spring.datasource.password=ewm
stats.server.id=stats-server
