server.port=0
logging.level.org.zalando.logbook.Logbook=TRACE
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=users
spring.datasource.password=users
management.endpoints.web.exposure.include=health,info
