spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:requests
spring.datasource.username=sa
spring.datasource.password=
eureka.client.enabled=false
spring.cloud.config.enabled=false
spring.sql.init.mode=always
