DROP TABLE IF EXISTS requests;
CREATE TABLE requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL
);
CREATE UNIQUE INDEX uq_request_event_user ON requests(event_id, requester_id);
