<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ru.practicum</groupId>
        <artifactId>explore-with-me</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>explore-with-me-stats-service</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>client</module>
        <module>dto</module>
        <module>stats-server</module>
        <module>avro-schemas</module>
        <module>proto-schemas</module>
        <module>collector</module>
        <module>aggregator</module>
        <module>analyzer</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <avro.version>1.11.4</avro.version>
        <grpc.version>1.63.0</grpc.version>
        <protobuf.version>3.25.3</protobuf.version>
        <grpc.spring.version>3.1.0.RELEASE</grpc.spring.version>
    </properties>

</project>